# Generated by Django 4.2.5 on 2024-03-18 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentofemployee',
            name='adharcard',
            field=models.FileField(null=True, upload_to='document/'),
        ),
        migrations.AlterField(
            model_name='documentofemployee',
            name='license',
            field=models.FileField(null=True, upload_to='document/'),
        ),
        migrations.AlterField(
            model_name='documentofemployee',
            name='pancard',
            field=models.FileField(null=True, upload_to='document/'),
        ),
        migrations.AlterField(
            model_name='documentofemployee',
            name='passport',
            field=models.FileField(null=True, upload_to='document/'),
        ),
        migrations.AlterField(
            model_name='documentofemployee',
            name='voterid',
            field=models.FileField(null=True, upload_to='document/'),
        ),
    ]
