# Generated by Django 4.2.5 on 2024-03-18 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_documentofemployee_adharcard_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='event',
            name='payment_status',
        ),
        migrations.AddField(
            model_name='sales',
            name='payment',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='sales',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('half paid', 'Half Paid'), ('paid', 'Paid')], default='not_yet', max_length=20),
        ),
    ]
