# Generated by Django 4.2.5 on 2024-03-18 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_event_payment_remove_event_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='reject',
            field=models.BooleanField(default=False),
        ),
    ]
