# Generated by Django 4.2.5 on 2024-03-19 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_lead_reject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='shift',
            field=models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening'), ('night', 'Night')], max_length=10),
        ),
    ]
