# Generated by Django 4.2.5 on 2024-03-19 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_attendance_marked_by_alter_attendance_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='client',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='dashboard.client'),
            preserve_default=False,
        ),
    ]
