# Generated by Django 4.2.5 on 2024-03-23 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_lead_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='convert',
            field=models.BooleanField(default=False),
        ),
    ]
