# Generated by Django 4.2.5 on 2024-03-23 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_attendance_convert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='convert',
        ),
        migrations.AddField(
            model_name='lead',
            name='convert',
            field=models.BooleanField(default=False),
        ),
    ]
