# Generated by Django 4.1.13 on 2024-03-28 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_alter_lead_options_remove_lead_convert_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='converted',
        ),
        migrations.AddField(
            model_name='lead',
            name='convert',
            field=models.BooleanField(default=False, verbose_name='Convert'),
        ),
    ]
