# Generated by Django 4.1.13 on 2024-03-30 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_remove_lead_converted_lead_convert'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='event',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='dashboard.event'),
            preserve_default=False,
        ),
    ]
