# Generated by Django 4.1.13 on 2024-03-31 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_alter_sales_amount_alter_sales_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lead', to='dashboard.event', verbose_name='Event'),
        ),
    ]
