# Generated by Django 4.1.13 on 2024-03-31 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_lead_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='sales',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='dashboard.sales'),
        ),
    ]
