# Generated by Django 4.1.13 on 2024-03-31 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_alter_lead_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='message',
            field=models.TextField(blank=True, default='remain', verbose_name='Message'),
        ),
    ]
