# Generated by Django 4.1.13 on 2024-04-08 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_alter_lead_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentofemployee',
            name='adharcard',
            field=models.FileField(blank=True, null=True, upload_to='document/'),
        ),
        migrations.AlterField(
            model_name='documentofemployee',
            name='license',
            field=models.FileField(blank=True, null=True, upload_to='document/'),
        ),
        migrations.AlterField(
            model_name='documentofemployee',
            name='pancard',
            field=models.FileField(blank=True, null=True, upload_to='document/'),
        ),
        migrations.AlterField(
            model_name='documentofemployee',
            name='passport',
            field=models.FileField(blank=True, null=True, upload_to='document/'),
        ),
        migrations.AlterField(
            model_name='documentofemployee',
            name='voterid',
            field=models.FileField(blank=True, null=True, upload_to='document/'),
        ),
    ]
