# Generated by Django 4.1.13 on 2024-04-08 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_alter_documentofemployee_adharcard_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='language',
            field=models.CharField(choices=[('hi', 'Hindi'), ('mr', 'Marathi'), ('en', 'English'), ('gu', 'Gujarati')], default=2, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='language',
            field=models.CharField(choices=[('hi', 'Hindi'), ('mr', 'Marathi'), ('en', 'English'), ('gu', 'Gujarati')], default='en-us', max_length=10),
        ),
    ]
