# Generated by Django 4.1.13 on 2024-04-08 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_remove_customuser_language_userlanguage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='language',
        ),
        migrations.AddField(
            model_name='usersettings',
            name='selected_theme',
            field=models.CharField(choices=[('light', 'Light Theme'), ('dark', 'Dark Theme')], default='light', max_length=20),
        ),
    ]
