"""
Django settings for finish project.

Generated by 'django-admin startproject' using Django 4.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

# Define the path to the directory containing wkhtmltopdf binary
BASE_DIR = Path(__file__).resolve().parent.parent



# Other Django settings...

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-fsz5s(5da0luobfz78g@j0l_#qgb7$dteuo4(pjzl^b#8u_n&6'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'pdfkit',
    'middlewar',
    'dashboard'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'dashboard.middleware.LanguageMiddleware',
    'dashboard.middleware.UserLanguageMiddleware',
    'dashboard.middleware.UserThemeMiddleware',
    'middlewar.theme.ThemeMiddleware'
]

ROOT_URLCONF = 'finish.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'template')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'finish.wsgi.application'
AUTH_USER_MODEL = 'dashboard.CustomUser'
AUTH_USER_MODEL = 'dashboard.CustomUser'


# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',  # Assuming your SQLite database file is in the project directory
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# settings.py
THEME_CHOICES = (
    ('light', 'Light Theme'),
    ('dark', 'Dark Theme'),
)



# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

from django.utils.translation import gettext_lazy as _
LANGUAGE_CODE = 'en-us'  # Default language code

LANGUAGES = [
    ('hi', _('Hindi')),
    ('mr', _('Marathi')),
    ('en', _('English')),
    ('gu', _('Gujarati')),
]

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True
USE_I18N = True

USE_L10N = True


# Your existing settings...

# Email configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'  # Replace with your SMTP host
EMAIL_PORT = 587  # Replace with your SMTP port
EMAIL_USE_TLS = True  # Set to True if your SMTP server requires TLS
EMAIL_HOST_USER = 'mujammilmaldar65@gmail.com'  # Replace with your email address
EMAIL_HOST_PASSWORD = 'zenn kywj vsph pghv'
DEFAULT_FROM_EMAIL = 'mujammilmaldar65@gmail.com'  # Replace with your email address

# Developer's email address
DEVELOPER_EMAIL = 'mujammilmaldar143@gmail.com' # Replace with the developer's email address
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
LOCALE_PATHS = [
    os.path.join(BASE_DIR, "locale"),
]

MEDIA_ROOT = os.path.join(BASE_DIR,"media")
MEDIA_URL = '/media/'

DATETIME_FORMAT = 'Y-m-d H:i:s'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
